server:
  port: 8090
spring:
  application:
    name: ssm
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://127.0.0.1:3306/education_0?useUnicode=true&characterEncoding=utf8\
                                 &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
                                 &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true"
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://127.0.0.1:3306/education_1?useUnicode=true&characterEncoding=utf8\
                                              &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
                                              &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true"
        username: root
        password: root
    sharding:
      tables:
        user:
          actual-data-nodes: ds$->{0..1}.acl_user_$->{0..1}
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds$->{id % 2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: acl_user_$->{id % 2}
          key-generator:
            cloumn: id
            type: SNOWFLAKE
      binding-tables: acl_user
      default-data-source-name: ds0
    props:
      sql:
        show: true

## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.ljq.demo.springboot.sharding.jdbc.model.entity
